language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gitbook-cli@2.3.0 ebook-convert@0.1.0 svgexport@0.3.2
  - sudo mkdir -p /opt/calibre && sudo rm -rf /opt/calibre/* && sudo wget -P /opt/calibre/txz https://download.calibre-ebook.com/2.85.1/calibre-2.85.1-x86_64.txz && sudo tar xvf /opt/calibre/txz/calibre-2.85.1-x86_64.txz -C /opt/calibre && sudo /opt/calibre/calibre_postinstall
  - sudo apt-get install -y xvfb imagemagick libxcomposite-dev
script:
  - gitbook pdf . _book/openmrs-android-client-user-guide.pdf
  - gitbook install && gitbook build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _book
  name: "Burke Mamlin"
  email: "burke@openmrs.org"
