language: node_js
node_js:
  - "node"
before_script:
  - npm install -g gitbook-cli@2.3.0 ebook-convert@0.1.0 svgexport@0.3.2
  - sudo -v && wget -nv -O- https://raw.githubusercontent.com/kovidgoyal/calibre/v2.85.1/setup/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - sudo apt-get install -y xvfb imagemagick libxcomposite-dev
script:
  - gitbook install && gitbook build
before_deploy:
  - gitbook pdf . _book/openmrs-android-client-user-guide.pdf
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: _book
  name: "Burke Mamlin"
  email: "burke@openmrs.org"
